//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dim_payroll_schedule
    {
        public int ID { get; set; }
        public string Week_Starting { get; set; }
        public string Week_Ending { get; set; }
        public string Submit_Day { get; set; }
        public string Pay_Day { get; set; }
        public string Settlement_Day { get; set; }
    }
}
