//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_web_monthly_financial_revenue_deposit
    {
        public int ID { get; set; }
        public System.DateTime Deposit_Date { get; set; }
        public string Amount { get; set; }
        public string Source { get; set; }
        public string Purpose { get; set; }
    }
}
