//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_web_monthly_financial_payroll
    {
        public int ID { get; set; }
        public System.DateTime Pay_Day { get; set; }
        public string Pay_Type { get; set; }
        public string Miles { get; set; }
        public string Base { get; set; }
        public string PPM { get; set; }
        public string Adjustments { get; set; }
        public string Pay { get; set; }
        public string Employee { get; set; }
    }
}
