//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rpt_weekly_production
    {
        public int ID { get; set; }
        public string Week_ID { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string Truck_Nbr { get; set; }
        public string Driver_Nbr { get; set; }
        public string Driver_Name { get; set; }
        public string Miles { get; set; }
        public string Gross { get; set; }
        public string Fuel { get; set; }
        public string Payroll { get; set; }
        public string Weekly_PPM { get; set; }
        public string Net { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
