//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_web_monthly_financial
    {
        public int ID { get; set; }
        public string Period { get; set; }
        public string Loads { get; set; }
        public string Miles { get; set; }
        public string PPM { get; set; }
        public string Revenue { get; set; }
        public string Payroll { get; set; }
        public string Fuel { get; set; }
        public string Expenses { get; set; }
        public string Net_PNL { get; set; }
    }
}
