//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dim_monthly_expense
    {
        public int ID { get; set; }
        public string Expense_Name { get; set; }
        public string Expense_Desc { get; set; }
        public string Join_Name { get; set; }
        public string Due_Day { get; set; }
        public string Expense_Group { get; set; }
        public string Amount_Est { get; set; }
        public string Monthly_Charge_Type { get; set; }
        public System.DateTime Active_StartDate { get; set; }
        public Nullable<System.DateTime> Active_EndDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
