//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dim_driver
    {
        public int ID { get; set; }
        public string Driver_Nbr { get; set; }
        public string Name { get; set; }
        public string Short_NM { get; set; }
        public string SSN { get; set; }
        public string CDL_Nbr { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string DOB { get; set; }
        public string Tax_Type { get; set; }
        public string Pay_Type { get; set; }
        public string PPM { get; set; }
        public string Hourly_Rate { get; set; }
        public string Flate_Rate { get; set; }
        public string ELD_Username { get; set; }
        public string ELD_password { get; set; }
        public string Active_Ind { get; set; }
        public Nullable<System.DateTime> Hire_Dt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PilotCard_Nbr { get; set; }
        public Nullable<System.DateTime> Pilot_Card_Start_Dt { get; set; }
        public Nullable<System.DateTime> Pilot_Card_End_Dt { get; set; }
        public string LovesCard_Nbr { get; set; }
        public Nullable<System.DateTime> Loves_Card_Start_Dt { get; set; }
        public Nullable<System.DateTime> Loves_Card_End_Dt { get; set; }
        public string ComDataCard_Nbr { get; set; }
        public Nullable<System.DateTime> ComData_Card_Start_Dt { get; set; }
        public Nullable<System.DateTime> ComData_Card_End_Dt { get; set; }
        public Nullable<System.DateTime> Term_Dt { get; set; }
    }
}
