//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fct_payroll
    {
        public int ID { get; set; }
        public System.DateTime Pay_Day { get; set; }
        public System.DateTime Week_Starting { get; set; }
        public System.DateTime Week_Ending { get; set; }
        public System.DateTime Submit_Day { get; set; }
        public decimal Miles { get; set; }
        public decimal Hours { get; set; }
        public int Days { get; set; }
        public string Pay_Type { get; set; }
        public decimal PPM { get; set; }
        public decimal Hour_Rate { get; set; }
        public decimal BasePay { get; set; }
        public string Driver_Nbr { get; set; }
        public string Driver { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
