//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fct_expense
    {
        public int ID { get; set; }
        public string Trans_Date { get; set; }
        public string Trans_Item { get; set; }
        public string Amount { get; set; }
        public string Method { get; set; }
        public string Authorized_By { get; set; }
        public string Purpose { get; set; }
        public string Exclusion_Reason { get; set; }
        public int Expense_ID { get; set; }
        public int Expense_IND { get; set; }
        public int Fuel_IND { get; set; }
        public int Payroll_IND { get; set; }
        public int Special_IND { get; set; }
        public string Active_IND { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
