//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fct_fuel_entry
    {
        public int ID { get; set; }
        public string Fuel_Date { get; set; }
        public string Fuel_Location { get; set; }
        public string Fuel_Type { get; set; }
        public string Fuel_Gallons { get; set; }
        public string Fuel_Amount { get; set; }
        public string Driver_Nbr { get; set; }
        public string Truck_Nbr { get; set; }
        public string Odometer { get; set; }
        public string Fuel_Receipt_URL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Driver_Nm { get; set; }
        public string Fuel_Paid_Ind { get; set; }
    }
}
