//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fct_payroll_hourly
    {
        public int ID { get; set; }
        public System.DateTime DateVal { get; set; }
        public string Day_Name { get; set; }
        public string Driver_Nbr { get; set; }
        public System.TimeSpan Clock_IN { get; set; }
        public System.TimeSpan Clock_OUT { get; set; }
        public Nullable<decimal> OnDuty_Hours_System { get; set; }
        public Nullable<decimal> OnDuty_Hours_Override { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
