//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_web_users
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Email_Alt { get; set; }
        public string UserType { get; set; }
        public string AdminType { get; set; }
        public string UserType_ID { get; set; }
        public string Financial_Expense_Access { get; set; }
        public string Financial_PNL_Access { get; set; }
        public string Payroll_Access { get; set; }
        public string HR_Access { get; set; }
        public string Active_Ind { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> Login_Cnt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
