//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_date_pnl_month
    {
        public long ID { get; set; }
        public string YearMonth { get; set; }
        public string Month_Nm { get; set; }
        public int CurrMonth { get; set; }
    }
}
