//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_date_week_of
    {
        public string Week_of { get; set; }
        public int Sort_Order { get; set; }
        public string Week_Ending { get; set; }
        public Nullable<long> ID { get; set; }
    }
}
