//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_date_week
    {
        public Nullable<long> ID { get; set; }
        public int DateID { get; set; }
        public string DateValue { get; set; }
        public Nullable<int> YearMonthNumber { get; set; }
        public Nullable<int> MonthDayNumber { get; set; }
        public Nullable<int> YearNumber { get; set; }
        public string DayName { get; set; }
        public string MonthName { get; set; }
        public string Week_of { get; set; }
        public string Week_Ending { get; set; }
    }
}
