//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fuel
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Trans_Date { get; set; }
        public string Location { get; set; }
        public string Amount { get; set; }
        public Nullable<decimal> Gallons { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Fuel_Type { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Trailer { get; set; }
        public string Odometer { get; set; }
        public string FuelSource { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> WebID { get; set; }
        public string State { get; set; }
        public string Trans_Date_str { get; set; }
    }
}
