//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_load_status
    {
        public int ID { get; set; }
        public string Load_Number { get; set; }
        public string Status { get; set; }
        public string Pickup_IND { get; set; }
        public string In_Progress_IND { get; set; }
        public string Delivered_IND { get; set; }
        public string In_Progress_MailSent_IND { get; set; }
        public string Delivered_MailSent_IND { get; set; }
        public Nullable<System.DateTime> Pickup_Status_DNT { get; set; }
        public Nullable<System.DateTime> Delivered_Status_DNT { get; set; }
        public string Paid_IND { get; set; }
        public string Driver_Paid_IND { get; set; }
        public string Driver_Paid_Status { get; set; }
    }
}
