//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_loads_detail_open
    {
        public string Week_of { get; set; }
        public string Week_Date { get; set; }
        public string Load_of_Week_Total { get; set; }
        public string Load_of_Week_Driver { get; set; }
        public string Load_Dt_Str { get; set; }
        public string Load_Date { get; set; }
        public string Load_of_Day_Total { get; set; }
        public string Load_of_Day_Driver { get; set; }
        public string Driver_Paid_Ind { get; set; }
        public string Driver_Paid_Status { get; set; }
        public string Load_Number { get; set; }
        public string Aux_Load_Number { get; set; }
        public string Cust_ID { get; set; }
        public string Customer_Nm { get; set; }
        public string Total_Miles { get; set; }
        public string Total_Load_Miles { get; set; }
        public string PPM { get; set; }
        public string T_PPM { get; set; }
        public string Driver_Payout { get; set; }
        public string Payout { get; set; }
        public string Detention_Payout { get; set; }
        public string Lumper_Charge { get; set; }
        public string Driver_Nbr { get; set; }
        public string Driver_Short_NM { get; set; }
        public string Driver { get; set; }
        public string Truck { get; set; }
        public string Trailer { get; set; }
        public string Status { get; set; }
        public string Weight { get; set; }
        public string Contents { get; set; }
        public string LTL { get; set; }
        public Nullable<int> LTL_PAY_STOPS { get; set; }
        public string Pickup_Location { get; set; }
        public string Pickup_Name { get; set; }
        public string Pickup_Address { get; set; }
        public string Pickup_Zip { get; set; }
        public string Pickup_Contact { get; set; }
        public string Pickup_Date { get; set; }
        public string Pickup_Time { get; set; }
        public string Pickup_Notes { get; set; }
        public string Deadhead_Miles { get; set; }
        public string Dropoff_1_Location { get; set; }
        public string Dropoff_1_Name { get; set; }
        public string Dropoff_1_Address { get; set; }
        public string Dropoff_1_Zip { get; set; }
        public string Dropoff_1_Contact { get; set; }
        public string Dropoff_1_Date { get; set; }
        public string Dropoff_1_Time { get; set; }
        public string Dropoff_1_Notes { get; set; }
        public string Pickup_DO1_Miles { get; set; }
        public string Dropoff_2_Location { get; set; }
        public string Dropoff_2_Name { get; set; }
        public string Dropoff_2_Address { get; set; }
        public string Dropoff_2_Zip { get; set; }
        public string Dropoff_2_Contact { get; set; }
        public string Dropoff_2_Date { get; set; }
        public string Dropoff_2_Time { get; set; }
        public string Dropoff_2_Notes { get; set; }
        public string DO1_DO2_Miles { get; set; }
        public string Dropoff_3_Location { get; set; }
        public string Dropoff_3_Name { get; set; }
        public string Dropoff_3_Address { get; set; }
        public string Dropoff_3_Zip { get; set; }
        public string Dropoff_3_Contact { get; set; }
        public string Dropoff_3_Date { get; set; }
        public string Dropoff_3_Time { get; set; }
        public string Dropoff_3_Notes { get; set; }
        public string DO2_DO3_Miles { get; set; }
        public string Dropoff_4_Location { get; set; }
        public string Dropoff_4_Name { get; set; }
        public string Dropoff_4_Address { get; set; }
        public string Dropoff_4_Zip { get; set; }
        public string Dropoff_4_Contact { get; set; }
        public string Dropoff_4_Date { get; set; }
        public string Dropoff_4_Time { get; set; }
        public string Dropoff_4_Notes { get; set; }
        public string DO3_DO4_Miles { get; set; }
        public string Dropoff_5_Location { get; set; }
        public string Dropoff_5_Name { get; set; }
        public string Dropoff_5_Address { get; set; }
        public string Dropoff_5_Zip { get; set; }
        public string Dropoff_5_Contact { get; set; }
        public string Dropoff_5_Date { get; set; }
        public string Dropoff_5_Time { get; set; }
        public string Dropoff_5_Notes { get; set; }
        public string DO4_DO5_Miles { get; set; }
        public string Dropoff_6_Location { get; set; }
        public string Dropoff_6_Name { get; set; }
        public string Dropoff_6_Address { get; set; }
        public string Dropoff_6_Zip { get; set; }
        public string Dropoff_6_Contact { get; set; }
        public string Dropoff_6_Date { get; set; }
        public string Dropoff_6_Time { get; set; }
        public string Dropoff_6_Notes { get; set; }
        public string DO5_DO6_Miles { get; set; }
        public string Dropoff_7_Location { get; set; }
        public string Dropoff_7_Name { get; set; }
        public string Dropoff_7_Address { get; set; }
        public string Dropoff_7_Zip { get; set; }
        public string Dropoff_7_Contact { get; set; }
        public string Dropoff_7_Date { get; set; }
        public string Dropoff_7_Time { get; set; }
        public string Dropoff_7_Notes { get; set; }
        public string DO6_DO7_Miles { get; set; }
        public string Load_Confirmation_URL { get; set; }
        public string Load_Confirmation_File_Type { get; set; }
        public string BOL_URL { get; set; }
        public string BOL_FILE_TYPE { get; set; }
        public string Route_ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Updatedby { get; set; }
    }
}
