//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_loads_summary_open
    {
        public int ID { get; set; }
        public string Week_of { get; set; }
        public string Week_of_str { get; set; }
        public string Load_of_Week_Total { get; set; }
        public string Load_of_Week_Driver { get; set; }
        public string Load_Dt_Str { get; set; }
        public string Load_Date { get; set; }
        public string Load_of_Day_Total { get; set; }
        public string Load_of_Day_Driver { get; set; }
        public string Load_Number { get; set; }
        public string Cust_ID { get; set; }
        public string Customer_Nm { get; set; }
        public string Total_Miles { get; set; }
        public string Driver_Payout { get; set; }
        public string Payout { get; set; }
        public string Final_Net_Payout { get; set; }
        public string PPM { get; set; }
        public string Driver_Nbr { get; set; }
        public string Driver { get; set; }
        public string Truck { get; set; }
        public string Status { get; set; }
        public string Driver_Paid_Ind { get; set; }
        public string Driver_Paid_Status { get; set; }
        public string Pickup { get; set; }
        public Nullable<System.DateTime> Pickup_Dt { get; set; }
        public string Pickup_Dt_str { get; set; }
        public string DropOff { get; set; }
        public string DropOff_Dt { get; set; }
    }
}
