//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payroll_period_summary
    {
        public int ID { get; set; }
        public string Week_Starting { get; set; }
        public string Week_Ending { get; set; }
        public string Submit_Day { get; set; }
        public string Pay_Day { get; set; }
        public string Fleetmatic_StartDate { get; set; }
        public string Fleetmatic_EndDate { get; set; }
        public Nullable<decimal> Total_Payroll { get; set; }
        public Nullable<decimal> Total_Month_Payroll { get; set; }
        public Nullable<int> Total_Employees { get; set; }
        public int Payroll_Run_Ind { get; set; }
    }
}
