//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payroll_web
    {
        public long ID { get; set; }
        public System.DateTime Pay_Day { get; set; }
        public System.DateTime Week_Starting { get; set; }
        public System.DateTime Week_Ending { get; set; }
        public System.DateTime Submit_Day { get; set; }
        public string Days { get; set; }
        public string Pay_Type { get; set; }
        public string Miles { get; set; }
        public string Hours { get; set; }
        public string PPM { get; set; }
        public string Hour_Rate { get; set; }
        public string BasePay { get; set; }
        public string Detention_Time { get; set; }
        public string Detention_Pay_Adjustment { get; set; }
        public string Stop_Count { get; set; }
        public string Stop_Pay_Adjustment { get; set; }
        public string Misc_Adjustment { get; set; }
        public string Misc_Adjustment_Notes { get; set; }
        public string Total_Adjustment_Amount { get; set; }
        public string Total_Pay { get; set; }
        public string Employee_Nbr { get; set; }
        public string Employee { get; set; }
        public string CreatedDate { get; set; }
    }
}
