//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sand_payout
    {
        public int ID { get; set; }
        public string Route_NM { get; set; }
        public string Region { get; set; }
        public string Mileage_Range { get; set; }
        public string Loaded_Mileage { get; set; }
        public string Deadhead_Mileage { get; set; }
        public string Total_Mileage { get; set; }
        public string Pickup_Nm { get; set; }
        public string Pickup_Address { get; set; }
        public string Pickup_Zip { get; set; }
        public string Dropoff_Nm { get; set; }
        public string Dropoff_Address { get; set; }
        public string Dropoff_Zip { get; set; }
        public string Full_Payout { get; set; }
        public string Percent_Payout { get; set; }
        public string Fuel_Surcharge { get; set; }
        public string Trailer_Fee { get; set; }
        public Nullable<decimal> Fuel_Surchage_Est { get; set; }
        public string Payout { get; set; }
        public string PPM { get; set; }
        public Nullable<decimal> Driver_Payout { get; set; }
        public string Payout_Before_Expense { get; set; }
        public string Active_Ind { get; set; }
    }
}
