//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_weekly_production
    {
        public long ID { get; set; }
        public Nullable<int> Week_ID { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public Nullable<decimal> Miles { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Fuel { get; set; }
        public Nullable<decimal> Payroll { get; set; }
        public Nullable<decimal> Weekly_PPM { get; set; }
        public Nullable<decimal> Net { get; set; }
    }
}
