//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_weekly_production_fuel
    {
        public long ID { get; set; }
        public string Date_Period { get; set; }
        public string Date_DT { get; set; }
        public string Fuel_Type { get; set; }
        public string Amount { get; set; }
        public string FuelSource { get; set; }
        public string Unit { get; set; }
        public string Name { get; set; }
    }
}
