//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxxExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_weekly_production_gross
    {
        public long ID { get; set; }
        public string Date_Period { get; set; }
        public string Truck { get; set; }
        public string Name { get; set; }
        public string Payout { get; set; }
        public string Load_Number { get; set; }
        public string Customer_nm { get; set; }
        public string Pickup { get; set; }
        public string Dropoff { get; set; }
        public Nullable<System.DateTime> Delivered_Dt { get; set; }
    }
}
